import { createIcons } from 'lucide';
import {
  ArrowRight, ArrowUp, Award, BadgeCheck, BedDouble, Blinds, Briefcase, Building2,
  Camera, CheckCircle, CloudRain, DoorOpen, Droplets, Factory, FileCheck, Flame,
  Globe, GraduationCap, Hammer, Landmark, Layers, LayoutGrid, Lightbulb, Map, MapPin,
  MessageCircle, Monitor, Moon, Package, PaintRoller, PanelsTopLeft, PartyPopper,
  ShieldCheck, Shirt, ShowerHead, Sparkles, SprayCan, Store, Sun, Timer, Truck,
  Users, Utensils, Wind, Wrench, Zap,
} from 'lucide';

const icons = {
  ArrowRight,
  ArrowUp,
  Award,
  BadgeCheck,
  BedDouble,
  Blinds,
  Briefcase,
  Building2,
  Camera,
  CheckCircle,
  CloudRain,
  DoorOpen,
  Droplets,
  Factory,
  FileCheck,
  Flame,
  Globe,
  GraduationCap,
  Hammer,
  Landmark,
  Layers,
  LayoutGrid,
  Lightbulb,
  Map,
  MapPin,
  MessageCircle,
  Monitor,
  Moon,
  Package,
  PaintRoller,
  PanelsTopLeft,
  PartyPopper,
  ShieldCheck,
  Shirt,
  ShowerHead,
  Sparkles,
  SprayCan,
  Store,
  Sun,
  Timer,
  Truck,
  Users,
  Utensils,
  Wind,
  Wrench,
  Zap,
};

window.lucide = { createIcons: (opts = {}) => createIcons({ ...opts, icons }) };